eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9005
spring:
  application:
    name: zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: client
    api-b:
      path: /api-b/**
      serviceId: client-1