server:
  port: 8888
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/houxi1234/demo/
          searchPaths: respo
          username:
          password:
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/